name: cube
channels:
    - defaults
    - nvidia
    - conda-forge
dependencies:
    - python=3.8
    - pip
    - numpy
    - scipy
    - numba
    - h5py
    - matplotlib
    - scikit-learn
    - jupyter
    - tqdm
    - protobuf
    - pytorch-cpu=1.13.0
    - jax=0.3.25
    - jaxlib=0.3.25=*cuda*
    - cudatoolkit=11.7
    - cuda-nvcc=11.7
    - cudnn
    - pip:
        - flax==0.6.0
        - optax==0.1.3
        - distrax==0.1.2
        - transformers==4.26.0
        - datasets==2.7.0
        - einops
        - tensorflow==2.11.0
        - dill
        - seaborn
        - absl-py
        - gtimer
        - joblib
        - wandb==0.13.5
        - ml_collections
        - gcsfs==2022.11.0
        - requests
        - jupyter_http_over_ws
        - evaluate==0.3.0
        - mujoco-py==2.1.2.14
        - gym[mujoco_py,classic_control]==0.23.0
        - git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rl
        - flask
        - lm-eval
        - jax_smi
        - pyext==0.7
        - dm_control==1.0.9
        - dm_env==1.6
        - mlxu==0.1.6 # just for local debug
